before:
  hooks:
  - go mod download

builds:
-
  env:
  - CGO_ENABLED=0
  asmflags:
  - all=-trimpath={{.Env.GOPATH}}
  ldflags:
  - -w -s -extldflags "-static"
  dir: ./cmd
  goos:
    - darwin
    - linux
    - windows
    - freebsd

archives:
-
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore'
